---
abstract: "It's new $module"
author:
  - 'Yosuke Furukawa <yosuke.furukawa@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.12.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-JSONParser
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Middleware::JSONParser:
    file: lib/Plack/Middleware/JSONParser.pm
    version: 0.01
requires:
  Hash::MultiValue: 0
  Plack::Middleware: 0
  Plack::Request: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/yosuke-furukawa/Plack-Middleware-JSONParser/issues
  homepage: https://github.com/yosuke-furukawa/Plack-Middleware-JSONParser
  repository: git://github.com/yosuke-furukawa/Plack-Middleware-JSONParser.git
version: 0.01
x_contributors:
  - 'Yosuke Furukawa <furukawa.yosuke@dena.jp>'
